Fix the following compilation error with clang.
Undefined symbols for architecture x86_64:
  "_parseFile", referenced from:
      _main in probSAT-db9ee7.o
  "_pickAndFlip", referenced from:
      _setupParameters in probSAT-db9ee7.o
      _main in probSAT-db9ee7.o
     (maybe you meant: _pickAndFlipVar)
  "_pickAndFlipNC", referenced from:
      _setupParameters in probSAT-db9ee7.o
      _main in probSAT-db9ee7.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The problem is that "inline" function declaration without
"extern" or "static" does not create external definition,
and therefore the above linking error can happen.
(c.f. ISO/IEC 9899:1999 §6.7.4/6)